
import __ASTRO_IMAGE_IMPORT_x9Ch6 from "./images/cda-fig-01-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_2j3hI7 from "./images/cda-fig-02-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_KDsMd from "./images/cda-fig-04-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_2wx8ee from "./images/cda-fig-05-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_ZLKl8G from "./images/cda-fig-06-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_Y8jik from "./images/cda-fig-07-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_Z2kaa4A from "./images/cda-fig-08-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_Z10fbDN from "./images/cda-fig-03-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
import __ASTRO_IMAGE_IMPORT_ZyguCz from "./images/cda-fig-09-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md";
export default new Map([["./images/cda-fig-01-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_x9Ch6], ["./images/cda-fig-02-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_2j3hI7], ["./images/cda-fig-04-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_KDsMd], ["./images/cda-fig-05-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_2wx8ee], ["./images/cda-fig-06-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_ZLKl8G], ["./images/cda-fig-07-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_Y8jik], ["./images/cda-fig-08-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_Z2kaa4A], ["./images/cda-fig-03-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_Z10fbDN], ["./images/cda-fig-09-en.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcda-context-direction-alignment-en.md", __ASTRO_IMAGE_IMPORT_ZyguCz]]);
		